spring:
  datasource:
    username: 'unforgettable'
    password: 'password'
    url: jdbc:postgresql://localhost:5432/library_database
  flyway:
    enabled: true
    url: jdbc:postgresql://localhost:5432/library_database
    user: 'unforgettable'
    password: 'password'
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true
  mail:
    host: 'smtp.gmail.com'
    port: 587
    username: 'sagittariusdew@gmail.com'
    password: 'ecmmwabvoyrtmrfe
'
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
application:
  security:
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      access-token:
        expiration: 600000000 # 86400000 # a day
      refresh-token:
        expiration: 604800000 # 7 days