spring:
  datasource:
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    url: ${DB_URL}
  flyway:
    enabled: true
    url: ${DB_URL}
    user: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true
  mail:
    host: 'smtp.gmail.com'
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
springdoc:
  swagger-ui:
    url: openapi.yaml
application:
  title: CrossUniversityLibrary
  version: 1.0.0
  security:
    jwt:
      secret-key: ${JWT_SECRET_KEY}
      access-token:
        expiration: 600000000 # 86400000 # a day
      refresh-token:
        expiration: 604800000 # 7 days
  aws:
    bucket: ${AWS_BUCKET}
    accessKeyId: ${AWS_ACCESS_KEY_ID}
    secretAccessKey: ${AWS_SECRET_ACCESS_KEY}
    region: ${AWS_REGION}